# Copyright (C) 2019 The MoKee Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/smartisan/sfo/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/smartisan/sfo/proprietary/vendor/bin/mm-qcamera-daemon:system/vendor/bin/mm-qcamera-daemon \
    vendor/smartisan/sfo/proprietary/vendor/bin/sensors.qcom:system/vendor/bin/sensors.qcom \
    vendor/smartisan/sfo/proprietary/vendor/bin/thermal-engine:system/vendor/bin/thermal-engine \
    vendor/smartisan/sfo/proprietary/vendor/etc/sensor_def_qcomdev.conf:system/vendor/etc/sensor_def_qcomdev.conf \
    vendor/smartisan/sfo/proprietary/vendor/etc/thermal-engine-8974.conf:system/vendor/etc/thermal-engine-8974.conf \
    vendor/smartisan/sfo/proprietary/vendor/lib/hw/camera.vendor.msm8974.so:system/vendor/lib/hw/camera.vendor.msm8974.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libarcsoft_asd.so:system/vendor/lib/libarcsoft_asd.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libarcsoft_night_shot.so:system/vendor/lib/libarcsoft_night_shot.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libarcsoft_panorama_burstcapture.so:system/vendor/lib/libarcsoft_panorama_burstcapture.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libarcsoft_pet_detection.so:system/vendor/lib/libarcsoft_pet_detection.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libmm-qcamera.so:system/vendor/lib/libmm-qcamera.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libmmcamera_interface.so:system/vendor/lib/libmmcamera_interface.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libmmjpeg_interface.so:system/vendor/lib/libmmjpeg_interface.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libqomx_core.so:system/vendor/lib/libqomx_core.so \
    vendor/smartisan/sfo/proprietary/vendor/firmware/BCM20795A1_001.002.012.0003.0083_Generic_I2C_NCD_Unsigned_configdata.ncd:system/vendor/firmware/BCM20795A1_001.002.012.0003.0083_Generic_I2C_NCD_Unsigned_configdata.ncd \
    vendor/smartisan/sfo/proprietary/vendor/lib/libsensors.msm8974.so:system/vendor/lib/libsensors.msm8974.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libarcsoft_beauty_shot.so:system/vendor/lib/libarcsoft_beauty_shot.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libchromatix_ov5648_common.so:system/vendor/lib/libchromatix_ov5648_common.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libchromatix_ov5648_default_video.so:system/vendor/lib/libchromatix_ov5648_default_video.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libchromatix_ov5648_preview.so:system/vendor/lib/libchromatix_ov5648_preview.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libchromatix_ov5648_snapshot.so:system/vendor/lib/libchromatix_ov5648_snapshot.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libchromatix_ov5648_zsl.so:system/vendor/lib/libchromatix_ov5648_zsl.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libjpegdhw.so:system/vendor/lib/libjpegdhw.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libjpegehw.so:system/vendor/lib/libjpegehw.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libmmcamera2_c2d_module.so:system/vendor/lib/libmmcamera2_c2d_module.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libmmcamera2_cpp_module.so:system/vendor/lib/libmmcamera2_cpp_module.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libmmcamera2_iface_modules.so:system/vendor/lib/libmmcamera2_iface_modules.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libmmcamera2_imglib_modules.so:system/vendor/lib/libmmcamera2_imglib_modules.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libmmcamera2_isp_modules.so:system/vendor/lib/libmmcamera2_isp_modules.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libmmcamera2_pproc_modules.so:system/vendor/lib/libmmcamera2_pproc_modules.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libmmcamera2_sensor_modules.so:system/vendor/lib/libmmcamera2_sensor_modules.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libmmcamera2_stats_algorithm.so:system/vendor/lib/libmmcamera2_stats_algorithm.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libmmcamera2_stats_modules.so:system/vendor/lib/libmmcamera2_stats_modules.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libmmcamera2_vpe_module.so:system/vendor/lib/libmmcamera2_vpe_module.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libmmcamera2_wnr_module.so:system/vendor/lib/libmmcamera2_wnr_module.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libmmcamera_faceproc.so:system/vendor/lib/libmmcamera_faceproc.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libmmcamera_foxconn_ccz00_eeprom.so:system/vendor/lib/libmmcamera_foxconn_ccz00_eeprom.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libmmcamera_hdr_gb_lib.so:system/vendor/lib/libmmcamera_hdr_gb_lib.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libmmcamera_hdr_lib.so:system/vendor/lib/libmmcamera_hdr_lib.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libmmcamera_imglib.so:system/vendor/lib/libmmcamera_imglib.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libmmcamera_m10mo.so:system/vendor/lib/libmmcamera_m10mo.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libmmcamera_ov5648.so:system/vendor/lib/libmmcamera_ov5648.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libmmcamera_tintless_algo.so:system/vendor/lib/libmmcamera_tintless_algo.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libmmcamera_tintless_bg_pca_algo.so:system/vendor/lib/libmmcamera_tintless_bg_pca_algo.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libmmcamera_tuning.so:system/vendor/lib/libmmcamera_tuning.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libmmcamera_wavelet_lib.so:system/vendor/lib/libmmcamera_wavelet_lib.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libmmipl.so:system/vendor/lib/libmmipl.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libmmjpeg.so:system/vendor/lib/libmmjpeg.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libmmqjpeg_codec.so:system/vendor/lib/libmmqjpeg_codec.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/liboemcamera.so:system/vendor/lib/liboemcamera.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libqomx_jpegdec.so:system/vendor/lib/libqomx_jpegdec.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libqomx_jpegenc.so:system/vendor/lib/libqomx_jpegenc.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libsensor1.so:system/vendor/lib/libsensor1.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libsensor_reg.so:system/vendor/lib/libsensor_reg.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libthermalclient.so:system/vendor/lib/libthermalclient.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libthermalioctl.so:system/vendor/lib/libthermalioctl.so

ifeq ($(QCPATH),)
PRODUCT_COPY_FILES += \
    vendor/smartisan/sfo/proprietary/vendor/bin/adsprpcd:system/vendor/bin/adsprpcd \
    vendor/smartisan/sfo/proprietary/vendor/bin/btnvtool:system/vendor/bin/btnvtool \
    vendor/smartisan/sfo/proprietary/vendor/bin/charger_monitor:system/vendor/bin/charger_monitor \
    vendor/smartisan/sfo/proprietary/vendor/bin/hci_qcomm_init:system/vendor/bin/hci_qcomm_init \
    vendor/smartisan/sfo/proprietary/vendor/bin/hvdcp:system/vendor/bin/hvdcp \
    vendor/smartisan/sfo/proprietary/vendor/bin/irsc_util:system/vendor/bin/irsc_util \
    vendor/smartisan/sfo/proprietary/vendor/bin/loc_launcher:system/vendor/bin/loc_launcher \
    vendor/smartisan/sfo/proprietary/vendor/bin/mm-pp-daemon:system/vendor/bin/mm-pp-daemon \
    vendor/smartisan/sfo/proprietary/vendor/bin/mpdecision:system/vendor/bin/mpdecision \
    vendor/smartisan/sfo/proprietary/vendor/bin/netmgrd:system/vendor/bin/netmgrd \
    vendor/smartisan/sfo/proprietary/vendor/bin/qmuxd:system/vendor/bin/qmuxd \
    vendor/smartisan/sfo/proprietary/vendor/bin/qseecomd:system/vendor/bin/qseecomd \
    vendor/smartisan/sfo/proprietary/vendor/bin/radish:system/vendor/bin/radish \
    vendor/smartisan/sfo/proprietary/vendor/bin/rfs_access:system/vendor/bin/rfs_access \
    vendor/smartisan/sfo/proprietary/vendor/bin/rmt_storage:system/vendor/bin/rmt_storage \
    vendor/smartisan/sfo/proprietary/vendor/bin/time_daemon:system/vendor/bin/time_daemon \
    vendor/smartisan/sfo/proprietary/vendor/etc/data/dsi_config.xml:system/vendor/etc/data/dsi_config.xml \
    vendor/smartisan/sfo/proprietary/vendor/etc/data/netmgr_config.xml:system/vendor/etc/data/netmgr_config.xml \
    vendor/smartisan/sfo/proprietary/vendor/etc/data/qmi_config.xml:system/vendor/etc/data/qmi_config.xml \
    vendor/smartisan/sfo/proprietary/vendor/firmware/a330_pfp.fw:system/vendor/firmware/a330_pfp.fw \
    vendor/smartisan/sfo/proprietary/vendor/firmware/a330_pm4.fw:system/vendor/firmware/a330_pm4.fw \
    vendor/smartisan/sfo/proprietary/vendor/firmware/cpp_firmware_v1_1_1.fw:system/vendor/firmware/cpp_firmware_v1_1_1.fw \
    vendor/smartisan/sfo/proprietary/vendor/firmware/cpp_firmware_v1_1_6.fw:system/vendor/firmware/cpp_firmware_v1_1_6.fw \
    vendor/smartisan/sfo/proprietary/vendor/firmware/cpp_firmware_v1_2_0.fw:system/vendor/firmware/cpp_firmware_v1_2_0.fw \
    vendor/smartisan/sfo/proprietary/vendor/firmware/venus.b00:system/vendor/firmware/venus.b00 \
    vendor/smartisan/sfo/proprietary/vendor/firmware/venus.b01:system/vendor/firmware/venus.b01 \
    vendor/smartisan/sfo/proprietary/vendor/firmware/venus.b02:system/vendor/firmware/venus.b02 \
    vendor/smartisan/sfo/proprietary/vendor/firmware/venus.b03:system/vendor/firmware/venus.b03 \
    vendor/smartisan/sfo/proprietary/vendor/firmware/venus.b04:system/vendor/firmware/venus.b04 \
    vendor/smartisan/sfo/proprietary/vendor/firmware/venus.mbn:system/vendor/firmware/venus.mbn \
    vendor/smartisan/sfo/proprietary/vendor/firmware/venus.mdt:system/vendor/firmware/venus.mdt \
    vendor/smartisan/sfo/proprietary/vendor/firmware/wcnss.b00:system/vendor/firmware/wcnss.b00 \
    vendor/smartisan/sfo/proprietary/vendor/firmware/wcnss.b01:system/vendor/firmware/wcnss.b01 \
    vendor/smartisan/sfo/proprietary/vendor/firmware/wcnss.b02:system/vendor/firmware/wcnss.b02 \
    vendor/smartisan/sfo/proprietary/vendor/firmware/wcnss.b04:system/vendor/firmware/wcnss.b04 \
    vendor/smartisan/sfo/proprietary/vendor/firmware/wcnss.b06:system/vendor/firmware/wcnss.b06 \
    vendor/smartisan/sfo/proprietary/vendor/firmware/wcnss.b07:system/vendor/firmware/wcnss.b07 \
    vendor/smartisan/sfo/proprietary/vendor/firmware/wcnss.b08:system/vendor/firmware/wcnss.b08 \
    vendor/smartisan/sfo/proprietary/vendor/firmware/wcnss.b09:system/vendor/firmware/wcnss.b09 \
    vendor/smartisan/sfo/proprietary/vendor/firmware/wcnss.mdt:system/vendor/firmware/wcnss.mdt \
    vendor/smartisan/sfo/proprietary/vendor/etc/permissions/qcnvitems.xml:system/vendor/etc/permissions/qcnvitems.xml \
    vendor/smartisan/sfo/proprietary/vendor/etc/permissions/qcrilhook.xml:system/vendor/etc/permissions/qcrilhook.xml \
    vendor/smartisan/sfo/proprietary/vendor/framework/qcnvitems.jar:system/vendor/framework/qcnvitems.jar \
    vendor/smartisan/sfo/proprietary/vendor/framework/qcrilhook.jar:system/vendor/framework/qcrilhook.jar \
    vendor/smartisan/sfo/proprietary/vendor/framework/qti-telephony-common.jar:system/vendor/framework/qti-telephony-common.jar \
    vendor/smartisan/sfo/proprietary/vendor/lib/libDiracAPI_SHARED.so:system/vendor/lib/libDiracAPI_SHARED.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libOmxVdecHevc.so:system/vendor/lib/libOmxVdecHevc.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libloc_api_v02.so:system/vendor/lib/libloc_api_v02.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/rfsa/adsp/libapps_mem_heap.so:system/vendor/lib/rfsa/adsp/libapps_mem_heap.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/rfsa/adsp/libdspCV_skel.so:system/vendor/lib/rfsa/adsp/libdspCV_skel.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/rfsa/adsp/libfastcvadsp.so:system/vendor/lib/rfsa/adsp/libfastcvadsp.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/rfsa/adsp/libfastcvadsp_skel.so:system/vendor/lib/rfsa/adsp/libfastcvadsp_skel.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/rfsa/adsp/libscveT2T_skel.so:system/vendor/lib/rfsa/adsp/libscveT2T_skel.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/soundfx/libdirac.so:system/vendor/lib/soundfx/libdirac.so \
    vendor/smartisan/sfo/proprietary/vendor/firmware/keymaster/keymaster.b00:system/vendor/firmware/keymaster/keymaster.b00 \
    vendor/smartisan/sfo/proprietary/vendor/firmware/keymaster/keymaster.b01:system/vendor/firmware/keymaster/keymaster.b01 \
    vendor/smartisan/sfo/proprietary/vendor/firmware/keymaster/keymaster.b02:system/vendor/firmware/keymaster/keymaster.b02 \
    vendor/smartisan/sfo/proprietary/vendor/firmware/keymaster/keymaster.b03:system/vendor/firmware/keymaster/keymaster.b03 \
    vendor/smartisan/sfo/proprietary/vendor/firmware/keymaster/keymaster.mdt:system/vendor/firmware/keymaster/keymaster.mdt \
    vendor/smartisan/sfo/proprietary/vendor/lib/egl/eglsubAndroid.so:system/vendor/lib/egl/eglsubAndroid.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/egl/libEGL_adreno.so:system/vendor/lib/egl/libEGL_adreno.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/egl/libGLESv1_CM_adreno.so:system/vendor/lib/egl/libGLESv1_CM_adreno.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/egl/libGLESv2_adreno.so:system/vendor/lib/egl/libGLESv2_adreno.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/egl/libq3dtools_adreno.so:system/vendor/lib/egl/libq3dtools_adreno.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/hw/flp.default.so:system/vendor/lib/hw/flp.default.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libC2D2.so:system/vendor/lib/libC2D2.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libCB.so:system/vendor/lib/libCB.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libHevcSwDecoder.so:system/vendor/lib/libHevcSwDecoder.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libNimsWrap.so:system/vendor/lib/libNimsWrap.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libOmxAacDec.so:system/vendor/lib/libOmxAacDec.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libOmxAmrwbplusDec.so:system/vendor/lib/libOmxAmrwbplusDec.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libOmxEvrcDec.so:system/vendor/lib/libOmxEvrcDec.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libOmxQcelp13Dec.so:system/vendor/lib/libOmxQcelp13Dec.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libOmxWmaDec.so:system/vendor/lib/libOmxWmaDec.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libOpenCL.so:system/vendor/lib/libOpenCL.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libQSEEComAPI.so:system/vendor/lib/libQSEEComAPI.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libRSDriver_adreno.so:system/vendor/lib/libRSDriver_adreno.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libacdbloader.so:system/vendor/lib/libacdbloader.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libacdbmapper.so:system/vendor/lib/libacdbmapper.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libacdbrtac.so:system/vendor/lib/libacdbrtac.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libadiertac.so:system/vendor/lib/libadiertac.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libadreno_utils.so:system/vendor/lib/libadreno_utils.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libadsprpc.so:system/vendor/lib/libadsprpc.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libaptX_encoder.so:system/vendor/lib/libaptX_encoder.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libaudcal.so:system/vendor/lib/libaudcal.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libaudioalsa.so:system/vendor/lib/libaudioalsa.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libbccQTI.so:system/vendor/lib/libbccQTI.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libbtnv.so:system/vendor/lib/libbtnv.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libc2d30-a3xx.so:system/vendor/lib/libc2d30-a3xx.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libc2d30-a4xx.so:system/vendor/lib/libc2d30-a4xx.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libconfigdb.so:system/vendor/lib/libconfigdb.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libdisp-aba.so:system/vendor/lib/libdisp-aba.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libdrmdiag.so:system/vendor/lib/libdrmdiag.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libdrmfs.so:system/vendor/lib/libdrmfs.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libdrmtime.so:system/vendor/lib/libdrmtime.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libdsi_netctrl.so:system/vendor/lib/libdsi_netctrl.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libfastcvadsp_stub.so:system/vendor/lib/libfastcvadsp_stub.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libfastcvopt.so:system/vendor/lib/libfastcvopt.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libflp.so:system/vendor/lib/libflp.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libgeofence.so:system/vendor/lib/libgeofence.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libgsl.so:system/vendor/lib/libgsl.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libizat_core.so:system/vendor/lib/libizat_core.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/liblbs_core.so:system/vendor/lib/liblbs_core.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/liblisten.so:system/vendor/lib/liblisten.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/liblistenhardware.so:system/vendor/lib/liblistenhardware.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/liblistenjni.so:system/vendor/lib/liblistenjni.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/liblistensoundmodel.so:system/vendor/lib/liblistensoundmodel.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libllvm-qcom.so:system/vendor/lib/libllvm-qcom.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libmm-abl-oem.so:system/vendor/lib/libmm-abl-oem.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libmm-abl.so:system/vendor/lib/libmm-abl.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libmmosal.so:system/vendor/lib/libmmosal.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libnetmgr.so:system/vendor/lib/libnetmgr.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/liboemcrypto.so:system/vendor/lib/liboemcrypto.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libperipheral_client.so:system/vendor/lib/libperipheral_client.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libqc-opt.so:system/vendor/lib/libqc-opt.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libqdi.so:system/vendor/lib/libqdi.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libqdp.so:system/vendor/lib/libqdp.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libqmi_cci.so:system/vendor/lib/libqmi_cci.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libqmi_common_so.so:system/vendor/lib/libqmi_common_so.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libqmi_csi.so:system/vendor/lib/libqmi_csi.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libqmi_csvt_srvc.so:system/vendor/lib/libqmi_csvt_srvc.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libqmi_encdec.so:system/vendor/lib/libqmi_encdec.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libqti-perfd-client.so:system/vendor/lib/libqti-perfd-client.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libril-qc-qmi-1.so:system/vendor/lib/libril-qc-qmi-1.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libril-qcril-hook-oem.so:system/vendor/lib/libril-qcril-hook-oem.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/librpmb.so:system/vendor/lib/librpmb.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/librs_adreno.so:system/vendor/lib/librs_adreno.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/librs_adreno_sha1.so:system/vendor/lib/librs_adreno_sha1.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libsc-a3xx.so:system/vendor/lib/libsc-a3xx.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libscale.so:system/vendor/lib/libscale.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libscve.so:system/vendor/lib/libscve.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libscve_stub.so:system/vendor/lib/libscve_stub.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libsmemlog.so:system/vendor/lib/libsmemlog.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libssd.so:system/vendor/lib/libssd.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libsystem_health_mon.so:system/vendor/lib/libsystem_health_mon.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/libxml.so:system/vendor/lib/libxml.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/soundfx/libqcbassboost.so:system/vendor/lib/soundfx/libqcbassboost.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/soundfx/libqcreverb.so:system/vendor/lib/soundfx/libqcreverb.so \
    vendor/smartisan/sfo/proprietary/vendor/lib/soundfx/libqcvirt.so:system/vendor/lib/soundfx/libqcvirt.so \
    vendor/smartisan/sfo/proprietary/vendor/qcril.db:system/vendor/qcril.db

PRODUCT_PACKAGES += \
    libmdmdetect \
    libTimeService \
    libdiag \
    libdsutils \
    libidl \
    libqcci_legacy \
    libqmi \
    libqmi_client_qmux \
    libqmiservices \
    libtime_genoff \
    qcrilmsgtunnel \
    TimeService \
    shutdownlistener
endif
